package com.codeforsurvival.db.entity;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Book generated by hbm2java
 */
@Entity
@Table(name = "book", catalog = "pdfreader")
public class Book implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 7501710916280301657L;
	private Long id;
	private String bookName;
	private String bookAuthor;
	private Double rating;
	private String bookLink;
	private Long addedBy;

	public Book() {
	}

	public Book(Long id, String bookName, String bookAuthor, Double rating,
			String bookLink, Long addedBy) {
		this.id = id;
		this.bookName = bookName;
		this.bookAuthor = bookAuthor;
		this.rating = rating;
		this.bookLink = bookLink;
		this.addedBy = addedBy;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "book_name", nullable = true, length = 65535)
	public String getBookName() {
		return this.bookName;
	}

	public void setBookName(String bookName) {
		this.bookName = bookName;
	}

	@Column(name = "book_author", nullable = true, length = 65535)
	public String getBookAuthor() {
		return this.bookAuthor;
	}

	public void setBookAuthor(String bookAuthor) {
		this.bookAuthor = bookAuthor;
	}

	@Column(name = "rating", nullable = true, precision = 12, scale = 0)
	public Double getRating() {
		return this.rating;
	}

	public void setRating(Double rating) {
		this.rating = rating;
	}

	@Column(name = "book_link", nullable = true, length = 65535)
	public String getBookLink() {
		return this.bookLink;
	}

	public void setBookLink(String bookLink) {
		this.bookLink = bookLink;
	}

	@Column(name = "added_by", nullable = false)
	public Long getAddedBy() {
		return addedBy;
	}

	public void setAddedBy(Long addedBy) {
		this.addedBy = addedBy;
	}

}
